export { default as IsBrainly } from "./IsBrainly"
export { default as isURL } from "./IsUrl"
export { default as createElement, CreateElementOptions } from "./createElement"
export { default as waitElement } from "./waitElement"
export { default as waitObject } from "./waitObject"
export { getStorage, setStorage } from "./storage"
export { default as DefaultReasons} from "./DefaultReasons"
